baseURL = "https://yusufatmaca.github.io/"
languageCode = "en"
title = "Yusuf Atmaca"

[params]
  description = "Programming, literature, etc."
  author = "Yusuf Atmaca"
  email = "yusufatmaca@protonmail.com"
  github = "yusufatmaca"
  linkedin = "in/yusufatmaca97"
  cv = "/yusuf-atmaca-cv.pdf"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = "table"
    lineNumbersInTable = true
    tabWidth = 2
    style = "github-dark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block  = [["\\[", "\\]"], ["$$", "$$"]]
        inline = [["\\(", "\\)"], ["$", "$"]]
[taxonomies]
  tag = "tags"

# Menü: üst nav için
[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "programming"
  url = "/programming/"
  weight = 2
[[menu.main]]
  name = "literature"
  url = "/literature/"
  weight = 3
